# Generated by Django 5.2.6 on 2025-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('DE', 'Dessert'), ('SN', 'Snack'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
