# Generated by Django 5.2.6 on 2025-09-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet_type',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON', 'Non-Vegetarian'), ('VGN', 'Vegan')], default='NON', max_length=3),
        ),
    ]
